name: 'komenda bash'
runs:
  using: composite
  steps:
    # Runs a single command using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        curl http://127.0.0.1:81
      shell: bash
